### ISSUE TITLE
Planner does not respect preconditions

### ISSUE THREAD

**Issue by rekino** [LAPKT-dev/LAPKT-public#22]
Hi,
I'm trying to solve the following planning problem:
[domain.txt](https://github.com/LAPKT-dev/LAPKT-public/files/1595893/domain.txt)
[problem.txt](https://github.com/LAPKT-dev/LAPKT-public/files/1595894/problem.txt)

the problem is that the planner doesn't respect the precondition that `(> (start ?l) (timeline ?r))`. to resolve the issue, planner should first do a `(shift-right-sixty SRY-THR)` and then `(asgn SRY-THR MOC SRY THR)`, but it does the later without shifting first. Am I doing something wrong?

EDIT:
I am using the docker image provided in docker hub

**Comment by nirlipo** [comment]
Hi Rekino,

Our planners in LAPKT do not handle numeric state variables, It's a feature that we haven't implemented yet, they just ignore them. We only use them to specify costs, not conditions.

To solve your problem you could try https://fai.cs.uni-saarland.de/hoffmann/metric-ff.html 

Cheers,

Nir
